"""empty message

Revision ID: b9a077f48469
Revises: 31364fb5c8d4
Create Date: 2022-08-21 21:48:28.182695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a077f48469'
down_revision = '31364fb5c8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.drop_column('post', 'data_created')
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.drop_column('user', 'data_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data_created', sa.DATETIME(), nullable=False))
    op.drop_column('user', 'date_created')
    op.add_column('post', sa.Column('data_created', sa.DATETIME(), nullable=False))
    op.drop_column('post', 'date_created')
    # ### end Alembic commands ###
